sudo: required
services:
  - docker

before_install:
  - docker build -t lucasbaier/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucasbaier/react-test npm test

after_success:
  - docker build -t lucasbaier/multi-client ./client
  - docker build -t lucasbaier/multi-nginx ./nginx
  - docker build -t lucasbaier/multi-server ./server
  - docker build -t lucasbaier/multi-worker ./worker
  # Take images and push to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lucasbaier/multi-client
  - docker push lucasbaier/multi-nginx
  - docker push lucasbaier/multi-server
  - docker push lucasbaier/multi-worker